version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: meunovoapp
      POSTGRES_PASSWORD: MNapp2023
      POSTGRES_DB: meunovoapp
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - nginx

volumes:
  postgres-data:
